apiVersion: v1
kind: ReplicationController
metadata:
  name: label-prod-web
  labels:
    environment: prod
    app: nginix
spec:
      replicas: 2
      selector: 
        environment: prod
        app: nginix
      template:
        metadata:
          name: label-prod-web
          labels:
            environment: prod
            app: nginix 
        spec:
          containers:
          - name: "nginix web server"
            image: nginix
            ports:
            - containerPort: 80
